import { useEffect, useRef, useState } from "react";
import {
  IconArrowRight as ArrowRight, IconArrowUpRight as ArrowUpRight, IconCheck as Check, IconChevronDown as ChevronDown, IconChevronRight as ChevronRight, IconFileText as FileText, IconFolderOpen as FolderOpen,
  IconHome as Home, IconMenu2 as Menu, IconMessageCircle as MessageCircle, IconDots as MoreHorizontal, IconEdit as PenLine, IconScale as Scale, IconSend as Send, IconShieldCheck as ShieldCheck,
  IconSparkles as Sparkles, IconUpload as Upload, IconX as X,
} from "@tabler/icons-react";

const copy = {
  de: {
    navHow: "So funktioniert’s", navFeatures: "Funktionen", navFaq: "FAQ", signIn: "Anmelden",
    eyebrow: "IHR FALL. KLAR STRUKTURIERT.",
    title: <>Klarheit für Ihren Fall.<br />Struktur für den<br />nächsten Schritt.</>,
    intro: "Ordnen Sie Ihre Unterlagen, verstehen Sie rechtliche Zusammenhänge und erstellen Sie Dokumententwürfe – auf Deutsch oder Englisch.",
    start: "Fall anlegen", demo: "Demo ansehen", meta: "Deutsch & Englisch  ·  Aktenzeichen  ·  Dokumententwürfe",
    badge: "Beispielfall", overview: "Übersicht", documents: "Dokumente", assistant: "Assistent", drafts: "Entwürfe",
    caseTitle: "Mietangelegenheit – Wohnung Berlin", inProgress: "In Bearbeitung", files: "Unterlagen", add: "Unterlagen hinzufügen",
    draft: "Schreiben vorbereiten", draftLabel: "Entwurf", missing: "Welche Unterlagen fehlen noch?", ask: "Frage zu Ihrem Fall …",
    stepsTitle: "In drei Schritten zum nächsten Schritt.", steps: [
      ["Fall beschreiben", "Schildern Sie kurz Ihr Anliegen und die wichtigsten Eckdaten."],
      ["Unterlagen hinzufügen", "Laden Sie relevante Dokumente sicher und übersichtlich hoch."],
      ["Entwurf vorbereiten", "Erhalten Sie verständliche Analysen und erstellen Sie Dokumententwürfe."],
    ],
    faqTitle: "Klarheit, bevor Sie starten.", faq: [["Ersetzt die Assistenz eine Rechtsberatung?", "Nein. Die Vorschläge dienen der Orientierung und ersetzen keine individuelle Beratung durch eine zugelassene Rechtsanwältin oder einen Rechtsanwalt."], ["Wo werden meine Unterlagen verarbeitet?", "Diese Vorschau speichert keine Dateien auf einem Server. Die Produktionsversion sollte die vereinbarte Hosting- und Datenschutzkonfiguration verwenden."], ["Kann ich auf Deutsch und Englisch arbeiten?", "Ja. Wechseln Sie die Sprache oben rechts; Aktenzeichen, Dokumente und Entwürfe bleiben dabei im selben Fall zusammen." ]],
    modalStart: "Neuen Fall anlegen", modalIntro: "Geben Sie die wichtigsten Eckdaten ein. Diese Vorschau speichert Ihre Eingaben nur im Browser.", subject: "Betreff", description: "Kurzbeschreibung", create: "Fall erstellen", cancel: "Abbrechen", close: "Schließen",
    loginTitle: "Anmelden", loginText: "Die Anmeldung wird in der Produktionsversion mit Ihrer eigenen Authentifizierung verbunden.", preview: "Vorschau öffnen", saved: "Fall angelegt – Vorschau aktualisiert.", uploadSaved: "Datei auf dem Server gespeichert.", error: "Der Fall konnte nicht gespeichert werden. Läuft das Backend auf Port 8001?", uploadError: "Die Datei konnte nicht gespeichert werden.", noCase: "Legen Sie zuerst einen Fall an.", limit: "Demo: keine Rechtsberatung, keine echte Dokumentenspeicherung.",
  },
  en: {
    navHow: "How it works", navFeatures: "Features", navFaq: "FAQ", signIn: "Sign in", eyebrow: "YOUR CASE. CLEARLY STRUCTURED.",
    title: <>Clarity for your case.<br />Structure for the<br />next step.</>, intro: "Organise your documents, understand the legal context and prepare document drafts – in German or English.", start: "Start a case", demo: "View demo", meta: "German & English  ·  Case reference  ·  Document drafts",
    badge: "Example case", overview: "Overview", documents: "Documents", assistant: "Assistant", drafts: "Drafts", caseTitle: "Tenancy matter – Berlin flat", inProgress: "In progress", files: "Documents", add: "Add documents", draft: "Prepare a letter", draftLabel: "Draft", missing: "Which documents are still missing?", ask: "Ask about your case …", stepsTitle: "Three steps to your next step.",
    steps: [["Describe your case", "Briefly share your concern and the key facts."], ["Add documents", "Upload relevant documents securely and clearly."], ["Prepare a draft", "Receive understandable analysis and prepare document drafts."]], faqTitle: "Clarity before you start.", faq: [["Does the assistant replace legal advice?", "No. Suggestions are for orientation and do not replace individual advice from a qualified lawyer."], ["Where are my documents processed?", "This preview does not save files to a server. Your production setup should use the agreed hosting and privacy configuration."], ["Can I work in German and English?", "Yes. Switch language above; your reference, documents and drafts stay together in one case."]], modalStart: "Start a new case", modalIntro: "Share the key facts. This preview keeps your input in the browser only.", subject: "Subject", description: "Short description", create: "Create case", cancel: "Cancel", close: "Close", loginTitle: "Sign in", loginText: "Production will connect sign-in to your own authentication system.", preview: "Open preview", saved: "Case created – preview updated.", uploadSaved: "File saved on the server.", error: "The case could not be saved. Is the API running on port 8001?", uploadError: "The file could not be saved.", noCase: "Create a case first.", limit: "Demo: no legal advice and no real document storage.",
  },
};

const files = ["Mietvertrag.pdf", "Schriftverkehr.pdf", "Fotos.zip"];

function Brand() { return <img className="brand-logo" src="/assets/schimmelpilz-logo.png" alt="Virtuelle Rechtsassistenz Schimmelpilz" />; }
function IconButton({ children, label, ...props }) { return <button className="icon-button" aria-label={label} {...props}>{children}</button>; }

function Dialog({ open, onClose, title, children, className = "" }) {
  const ref = useRef(null);
  useEffect(() => { const el = ref.current; if (!el) return; if (open && !el.open) el.showModal(); if (!open && el.open) el.close(); }, [open]);
  return <dialog ref={ref} className={`dialog ${className}`} onClose={onClose} onCancel={onClose}><div className="dialog-card"><button className="dialog-close" onClick={onClose} aria-label="Schließen"><X size={18} /></button><div className="dialog-kicker">AI RECHTSASSISTENZ</div><h2>{title}</h2>{children}</div></dialog>;
}

function CaseWorkspace({ lang, t, activeTab, setActiveTab, onFile, onDraft, caseTitle, reference, uploadedFiles, question, setQuestion, answer, askAssistant }) {
  const tabs = [["overview", t.overview, Home], ["documents", t.documents, FileText], ["drafts", t.drafts, PenLine], ["assistant", t.assistant, MessageCircle]];
  return <div className="workspace-shell" id="preview">
    <div className="workspace-sidebar"><Brand /><div className="workspace-nav">{tabs.map(([id, label, I]) => <button key={id} className={activeTab === id ? "selected" : ""} onClick={() => setActiveTab(id)}><I size={18} />{label}</button>)}</div><div className="sidebar-foot"><ShieldCheck size={16} /> {lang === "de" ? "Privat & übersichtlich" : "Private & clear"}</div></div>
    <div className="workspace-content"><div className="workspace-topline"><div><div className="small-label">SCH-2026-000123</div><h2>{lang === "de" ? "Ihre Fallübersicht" : "Your case overview"}</h2></div><span className="case-badge">{t.badge}</span></div>
      <div className="case-heading"><div><h3>{caseTitle}</h3><div className="case-subline">{reference} <span className="status-pill">{t.inProgress}</span></div></div><IconButton label="Weitere Optionen"><MoreHorizontal size={21} /></IconButton></div>
      <div className="case-tabs">{tabs.slice(0,3).map(([id, label]) => <button key={id} className={activeTab === id ? "active" : ""} onClick={() => setActiveTab(id)}>{label}</button>)}</div>
      {activeTab === "overview" && <><section className="panel file-panel"><div className="panel-title"><h4>{t.files}</h4><button className="small-action" onClick={onFile}><Upload size={15} /> {t.add}</button></div>{files.concat(uploadedFiles).map((f, i) => <button className="file-row" key={`${f}-${i}`} onClick={() => onDraft(f)}><span className={`file-icon ${i === 2 ? "blue" : "red"}`}><FileText size={16} /></span><span>{f}</span><small>{uploadedFiles.includes(f) ? "Server · gespeichert" : i === 2 ? "ZIP · 12,8 MB" : `PDF · ${i ? "1,4" : "2,1"} MB`}</small><MoreHorizontal size={16} /></button>)}</section><section className="panel draft-panel"><div className="panel-title"><h4>{t.draft}</h4><span className="draft-chip">{t.draftLabel}</span></div><p>{lang === "de" ? "Sehr geehrte Damen und Herren," : "Dear Sir or Madam,"}</p><p>{lang === "de" ? "hiermit nehme ich Bezug auf den bestehenden Mietvertrag und die aufgetretenen Mängel in der Wohnung." : "I am writing regarding the existing tenancy agreement and the defects that have appeared in the flat."}</p><p>{lang === "de" ? "Bitte lassen Sie mir zeitnah eine schriftliche Stellungnahme zu den genannten Punkten zukommen." : "Please send me a written response to these points at your earliest convenience."}</p><button className="text-link" onClick={() => onDraft("draft")}>{lang === "de" ? "Entwurf bearbeiten" : "Edit draft"} <ArrowUpRight size={15} /></button></section></>}
      {activeTab === "documents" && <section className="panel empty-panel"><FileText size={30} /><h4>{lang === "de" ? "Ihre Unterlagen" : "Your documents"}</h4><p>{lang === "de" ? "Laden Sie Dokumente hoch, um Ihren Fall zu ordnen." : "Upload documents to organise your case."}</p><button className="small-action" onClick={onFile}><Upload size={15} /> {t.add}</button></section>}
      {activeTab === "drafts" && <section className="panel empty-panel"><PenLine size={30} /><h4>{t.draft}</h4><p>{lang === "de" ? "Entwürfe erscheinen hier, sobald Sie einen Brief vorbereiten." : "Drafts appear here as you prepare a letter."}</p><button className="small-action" onClick={() => onDraft("draft")}>{lang === "de" ? "Entwurf öffnen" : "Open draft"}</button></section>}
      {activeTab === "assistant" && <section className="panel assistant-panel"><div className="assistant-title"><span className="assistant-avatar"><MessageCircle size={17} /></span><h4>{lang === "de" ? "Ihr KI-Assistent" : "Your AI assistant"}</h4></div><div className="assistant-answer">{answer || t.missing}</div><div className="assistant-input"><input aria-label={t.ask} value={question} onChange={e => setQuestion(e.target.value)} placeholder={t.ask} onKeyDown={e => e.key === "Enter" && askAssistant()} /><button onClick={askAssistant} aria-label={lang === "de" ? "Frage senden" : "Send question"}><Send size={17} /></button></div><small className="demo-note">{t.limit}</small></section>}
    </div><div className="workspace-chat" onClick={() => setActiveTab("assistant")}><div className="chat-head"><span className="assistant-avatar"><MessageCircle size={16} /></span><strong>{lang === "de" ? "Ihr KI-Assistent" : "Your AI assistant"}</strong><MoreHorizontal size={17} /></div><div className="chat-suggestion">{t.missing}</div><div className="chat-input"><span>{t.ask}</span><Send size={16} /></div></div>
  </div>;
}

export function App() {
  const [lang, setLang] = useState("de"); const t = copy[lang];
  const [modal, setModal] = useState(null); const [activeTab, setActiveTab] = useState("overview"); const [menu, setMenu] = useState(false);
  const [caseTitle, setCaseTitle] = useState(t.caseTitle); const [caseId, setCaseId] = useState(""); const [reference, setReference] = useState("SCH-2026-000123"); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [uploadedFiles, setUploadedFiles] = useState([]); const [toast, setToast] = useState(""); const [savingCase, setSavingCase] = useState(false); const fileRef = useRef(null); const previewRef = useRef(null);
  useEffect(() => { document.documentElement.lang = lang; document.title = lang === "de" ? "Virtuelle Rechtsassistenz Schimmelpilz" : "Virtual Legal Assistant Schimmelpilz"; setCaseTitle((current) => [copy.de.caseTitle, copy.en.caseTitle].includes(current) ? t.caseTitle : current); }, [lang, t.caseTitle]);
  const showToast = (message) => { setToast(message); window.setTimeout(() => setToast(""), 3500); };
  const apiBase = import.meta.env.VITE_API_BASE || (window.location.port === "4173" ? "http://127.0.0.1:8001" : "");
  const startCase = async e => { e.preventDefault(); if (!subject.trim() || description.trim().length < 10 || savingCase) return; setSavingCase(true); try { const response = await fetch(`${apiBase}/api/cases`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: subject.trim(), description: description.trim(), language: lang }) }); if (!response.ok) throw new Error("case create failed"); const created = await response.json(); setCaseId(created.id); setReference(created.reference); setCaseTitle(created.title); setModal(null); setSubject(""); setDescription(""); showToast(`${t.saved} ${created.reference}`); previewRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }); } catch { showToast(t.error); } finally { setSavingCase(false); } };
  const onFile = () => { if (!caseId) { showToast(t.noCase); return; } fileRef.current?.click(); };
  const onFiles = async e => { const selected = [...e.target.files]; if (!selected.length || !caseId) return; try { const saved = []; for (const file of selected) { const body = new FormData(); body.append("file", file); const response = await fetch(`${apiBase}/api/cases/${caseId}/documents`, { method: "POST", body }); if (!response.ok) throw new Error("upload failed"); saved.push(file.name); } setUploadedFiles(current => [...current, ...saved]); showToast(`${saved.length} ${t.uploadSaved}`); } catch { showToast(t.uploadError); } finally { e.target.value = ""; } };
  const askAssistant = () => { if (!question.trim()) return; setAnswer(lang === "de" ? "Für eine erste Einordnung fehlen meist Mietvertrag, Schriftverkehr und eine kurze Chronologie. Bitte lassen Sie die konkrete Bewertung anwaltlich prüfen." : "For an initial review, the tenancy agreement, correspondence and a short timeline are usually helpful. Have the specific assessment checked by a qualified lawyer."); };
  return <div className="site"><a className="skip-link" href="#main">Zum Inhalt springen</a><header className="site-header"><a className="brand-link" href="#top"><Brand /></a><nav className={menu ? "open" : ""}><a href="#how" onClick={() => setMenu(false)}>{t.navHow}</a><a href="#features" onClick={() => setMenu(false)}>{t.navFeatures}</a><a href="#faq" onClick={() => setMenu(false)}>{t.navFaq}</a><span className="nav-divider" /><button className={lang === "de" ? "language active" : "language"} onClick={() => setLang("de")}>DE</button><span className="language-sep">|</span><button className={lang === "en" ? "language active" : "language"} onClick={() => setLang("en")}>EN</button><button className="header-login" onClick={() => setModal("login")}>{t.signIn}</button></nav><button className="menu-toggle" aria-label="Menü" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>
    <main id="main"><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><button className="primary-button" onClick={() => setModal("case")}>{t.start} <ArrowRight size={20} /></button><button className="secondary-button" onClick={() => previewRef.current?.scrollIntoView({ behavior: "smooth", block: "center" })}>{t.demo}</button></div><p className="hero-meta">{t.meta}</p></div><div className="hero-visual"><div className="visual-wash" /><div ref={previewRef}><CaseWorkspace lang={lang} t={t} activeTab={activeTab} setActiveTab={setActiveTab} onFile={onFile} onDraft={() => setModal("draft")} caseTitle={caseTitle} reference={reference} uploadedFiles={uploadedFiles} question={question} setQuestion={setQuestion} answer={answer} askAssistant={askAssistant} /></div><span className="visual-caption">{lang === "de" ? "Designkonzept · Vorschau" : "Design concept · Preview"}</span></div></section>
      <section className="steps-section" id="how"><p className="section-kicker">{lang === "de" ? "SO FUNKTIONIERT’S" : "HOW IT WORKS"}</p><h2>{t.stepsTitle}</h2><div className="steps-grid">{t.steps.map(([title, text], i) => <div className="step" key={title}><div className="step-number">0{i + 1}</div><div className="step-icon">{i === 0 ? <FileText /> : i === 1 ? <Upload /> : <PenLine />}</div><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
      <section className="feature-section" id="features"><div className="section-heading"><p className="section-kicker">{t.navFeatures}</p><h2>{lang === "de" ? "Alles an einem Ort." : "Everything in one place."}</h2></div><div className="feature-cards"><article><Scale size={22} /><h3>{lang === "de" ? "Aktenzeichen im Mittelpunkt" : "Your reference at the centre"}</h3><p>{lang === "de" ? "Jeder Fall erhält eine klare Struktur – von der ersten Notiz bis zum fertigen Entwurf." : "Every case gets a clear structure, from the first note to a finished draft."}</p></article><article><FolderOpen size={22} /><h3>{lang === "de" ? "Unterlagen geordnet" : "Documents, organised"}</h3><p>{lang === "de" ? "Behalten Sie Überblick über Verträge, Schriftverkehr und Fotos." : "Keep track of contracts, correspondence and photos."}</p></article><article><Sparkles size={22} /><h3>{lang === "de" ? "Verständlich formuliert" : "Easy to understand"}</h3><p>{lang === "de" ? "Analysen und Entwürfe, die Sie Schritt für Schritt nachvollziehen können." : "Analysis and drafts you can follow step by step."}</p></article></div></section>
      <section className="faq-section" id="faq"><div className="section-heading"><p className="section-kicker">FAQ</p><h2>{t.faqTitle}</h2></div><div className="faq-list">{t.faq.map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={19} /></summary><p>{a}</p></details>)}</div></section>
    </main><footer className="site-footer"><Brand /><span>{t.limit}</span><a href="#faq">Datenschutz & Hinweise <ChevronRight size={15} /></a></footer>
    <input ref={fileRef} className="visually-hidden" type="file" multiple accept=".pdf,.doc,.docx,.png,.jpg,.jpeg,.zip" onChange={onFiles} />
    <Dialog open={modal === "case"} onClose={() => setModal(null)} title={t.modalStart}><p className="dialog-intro">{t.modalIntro}</p><form onSubmit={startCase}><label>{t.subject}<input required maxLength="90" value={subject} onChange={e => setSubject(e.target.value)} placeholder={t.caseTitle} /></label><label>{t.description}<textarea required minLength="10" maxLength="1000" value={description} onChange={e => setDescription(e.target.value)} placeholder={lang === "de" ? "Was ist passiert?" : "What happened?"} /></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={() => setModal(null)}>{t.cancel}</button><button type="submit" className="primary-button" disabled={savingCase}>{savingCase ? "…" : t.create} {!savingCase && <ArrowRight size={18} />}</button></div></form></Dialog>
    <Dialog open={modal === "login"} onClose={() => setModal(null)} title={t.loginTitle}><p className="dialog-intro">{t.loginText}</p><div className="login-preview"><ShieldCheck size={21} /><span>{t.limit}</span></div><button className="primary-button full-button" onClick={() => { setModal(null); previewRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }); }}>{t.preview} <ArrowRight size={18} /></button></Dialog>
    <Dialog open={modal === "draft"} onClose={() => setModal(null)} title={t.draft}><p className="dialog-intro">{t.limit}</p><textarea className="draft-editor" defaultValue={lang === "de" ? "Sehr geehrte Damen und Herren,\n\nhiermit nehme ich Bezug auf den bestehenden Mietvertrag und die aufgetretenen Mängel in der Wohnung.\n\nMit freundlichen Grüßen" : "Dear Sir or Madam,\n\nI am writing regarding the existing tenancy agreement and the defects that have appeared in the flat.\n\nYours sincerely"} /><div className="dialog-actions"><button className="secondary-button" onClick={() => setModal(null)}>{t.cancel}</button><button className="primary-button" onClick={() => { setModal(null); showToast(lang === "de" ? "Entwurf lokal aktualisiert." : "Draft updated locally."); }}><Check size={18} /> {lang === "de" ? "Speichern" : "Save"}</button></div></Dialog>
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}
  </div>;
}
