import { useState } from "react";
import { IconLayoutDashboard, IconFolders, IconFileText, IconEdit, IconSearch, IconPlus, IconLogout, IconArrowRight } from "@tabler/icons-react";
import { CaseWorkspace } from "./CaseWorkspace.jsx";
import { FeatureOverview } from "./FeatureOverview.jsx";
import { intakeCopy } from "./CaseIntake.jsx";

export function Dashboard({ lang, setLang, t, user, storage, view, setView, onNewCase, onLogout, workspaceProps }) {
  const [filter, setFilter] = useState("");
  const de = lang === "de";
  const labels = de ? { overview: "Übersicht", cases: "Akten", documents: "Dokumente", drafts: "Entwürfe", research: "Recherche", account: "Kontaktdaten", title: "Ihr Arbeitsbereich", intro: "Akten führen, Unterlagen ordnen und den nächsten Schriftsatz vorbereiten.", empty: "Noch keine Akten angelegt", emptyText: "Beginnen Sie mit einer strukturierten Fallaufnahme. Alle Unterlagen und Entwürfe werden dieser Akte zugeordnet.", search: "Akten durchsuchen", open: "Akte öffnen", logout: "Abmelden", files: "Dokumente", records: "Akten", deadlines: "Erfasste Fristen", deadlineNote: "Manuell erfasst · keine automatische Überwachung", back: "Zur Aktenliste" } : { overview: "Overview", cases: "Case files", documents: "Documents", drafts: "Drafts", research: "Research", account: "Contact details", title: "Your workspace", intro: "Manage files, organise documents and prepare the next document.", empty: "No case files yet", emptyText: "Start with a structured intake. All documents and drafts will belong to that file.", search: "Search case files", open: "Open file", logout: "Sign out", files: "Documents", records: "Case files", deadlines: "Recorded deadlines", deadlineNote: "Manually recorded · no automatic monitoring", back: "Back to case list" };
  const navigation = [["overview", IconLayoutDashboard], ["cases", IconFolders], ["documents", IconFileText], ["drafts", IconEdit], ["research", IconSearch]];
  const filtered = storage.cases.filter(item => `${item.reference} ${item.title} ${item.details?.client_name || ""} ${item.details?.opponent_name || ""}`.toLocaleLowerCase().includes(filter.toLocaleLowerCase()));
  const isWorkspace = ["case", "documents", "drafts"].includes(view) && storage.selectedCase;
  const open = id => { workspaceProps.onSelectCase(id); setView("case"); };
  const changeView = id => { setView(id); if (id === "documents" || id === "drafts") workspaceProps.setActiveTab(id); };
  const address = `${user.street}, ${user.postal_code} ${user.city}, ${user.country}`;
  return <div className="application-layout">
    <aside className="app-sidebar"><a href="#" className="app-brand" onClick={event => { event.preventDefault(); setView("overview"); }}><img className="brand-logo" src="/assets/schimmelpilz-logo.png" alt="Virtuelle Rechtsassistenz Schimmelpilz" /></a><div className="account-type">{intakeCopy[lang][user.audience]}</div><nav aria-label={de ? "Arbeitsbereich" : "Workspace"}>{navigation.map(([id, Icon]) => <button key={id} onClick={() => changeView(id)} className={view === id || view === "case" && id === "cases" ? "active" : ""}><Icon size={20} />{labels[id]}</button>)}</nav><div className="sidebar-account"><strong>{user.organisation || user.full_name}</strong><small>{user.email}</small><button onClick={() => setView("account")}>{labels.account}</button><button onClick={onLogout}><IconLogout size={17} />{labels.logout}</button></div></aside>
    <div className="app-main"><header className="app-topbar"><div><span className="section-kicker">SCHIMMELPILZ</span><h1>{view === "case" ? labels.cases : labels[view] || labels.title}</h1></div><div className="app-topbar-actions"><div className="app-languages"><button className={lang === "de" ? "language active" : "language"} onClick={() => setLang("de")}>DE</button><button className={lang === "en" ? "language active" : "language"} onClick={() => setLang("en")}>EN</button></div><button className="primary-button" onClick={onNewCase}><IconPlus size={18} />{t.start}</button></div></header>
      <main className="app-content">
        {storage.loading && <p className="storage-notice" role="status">{t.loadingCases}</p>}
        {storage.loadError && <p className="storage-notice storage-error" role="alert">{t.loadError} <button onClick={() => storage.reload()}>{t.retry}</button></p>}
        {view === "research" ? <FeatureOverview lang={lang} onDraft={() => workspaceProps.onDraft()} /> : view === "account" ? <section className="account-card"><h2>{labels.account}</h2><dl><div><dt>{de ? "Name" : "Name"}</dt><dd>{user.full_name}</dd></div>{user.organisation && <div><dt>{de ? "Organisation" : "Organisation"}</dt><dd>{user.organisation}</dd></div>}<div><dt>E-Mail</dt><dd>{user.email}</dd></div><div><dt>{de ? "Anschrift" : "Address"}</dt><dd>{address}</dd></div>{user.phone && <div><dt>{de ? "Telefon" : "Phone"}</dt><dd>{user.phone}</dd></div>}</dl></section> : isWorkspace ? <><button className="text-link back-to-cases" onClick={() => setView("cases")}>← {labels.back}</button><CaseWorkspace {...workspaceProps} lang={lang} t={t} storage={storage} appMode /></> : <>
          {view === "overview" && <><div className="workspace-welcome"><h2>{labels.title}</h2><p>{labels.intro}</p></div><div className="workspace-stats"><article><span>{labels.records}</span><strong>{storage.cases.length}</strong></article><article><span>{labels.files}</span><strong>{storage.cases.reduce((count, item) => count + item.documents.length, 0)}</strong></article><article><span>{labels.drafts}</span><strong>{storage.cases.reduce((count, item) => count + item.drafts.length, 0)}</strong></article></div></>}
          {!storage.cases.length && !storage.loading ? <section className="empty-workspace"><IconFolders size={38} /><h2>{labels.empty}</h2><p>{labels.emptyText}</p><button className="primary-button" onClick={onNewCase}>{t.start}<IconArrowRight size={18} /></button></section> : <section className="case-list"><div className="case-list-heading"><h2>{labels.records}</h2><input type="search" aria-label={labels.search} placeholder={labels.search} value={filter} onChange={event => setFilter(event.target.value)} /></div>{filtered.length ? <div className="case-list-rows">{filtered.map(item => <button key={item.id} onClick={() => open(item.id)} className="case-list-row"><div><span className="case-reference">{item.reference}</span><h3>{item.title}</h3><p>{[item.details?.client_name, item.details?.opponent_name].filter(Boolean).join(" · ") || (de ? "Beteiligte noch offen" : "Parties to be completed")}</p></div><div className="case-list-meta"><span>{item.documents.length} {labels.files} · {item.drafts.length} {labels.drafts}</span><span>{labels.open}<IconArrowRight size={17} /></span></div></button>)}</div> : <p className="storage-empty">{de ? "Keine passenden Akten gefunden." : "No matching files found."}</p>}</section>}
          {view === "overview" && <section className="deadline-list"><h2>{labels.deadlines}</h2><p className="field-help">{labels.deadlineNote}</p>{storage.cases.filter(item => item.details?.deadline).sort((a, b) => a.details.deadline.localeCompare(b.details.deadline)).map(item => <button key={item.id} onClick={() => open(item.id)}><span>{new Date(`${item.details.deadline}T12:00:00`).toLocaleDateString(de ? "de-DE" : "en-GB")}</span><strong>{item.reference}</strong><span>{item.details.deadline_note || item.title}</span></button>)}</section>}
        </>}
      </main><footer className="app-footer">{t.limit}</footer>
    </div>
  </div>;
}
