import {reviewLabels} from './DraftReview.jsx';
import { useState } from "react";
import { IconArrowUpRight, IconCalendar, IconCheck, IconEdit, IconFileText, IconPlus, IconUpload } from "@tabler/icons-react";
import { API_BASE } from "./useCaseStorage.js";
import { DocumentReview } from "./DocumentReview.jsx";
import { draftCopy } from "./draftTemplates.js";
import { intakeCopy } from "./CaseIntake.jsx";
import { activityLabels, activityRows, caseMatches, dateLabel, localToday, matches, partyRows, statusLabels, taskRows } from "./workbench.js";

export function Empty({ lang, children }) {
  return <p className="desk-empty">{children || (lang === "de" ? "Noch keine Einträge in diesem Bereich." : "No entries in this section yet.")}</p>;
}

export function Status({ item, lang }) {
  const status = item.details?.status || "active";
  return <span className={`desk-status ${status}`}>{statusLabels[lang][status] || statusLabels[lang].active}</span>;
}

export function CaseTable({ cases, lang, query = "", status = "all", open, compact = false }) {
  const c = intakeCopy[lang], de = lang === "de";
  const rows = cases.filter(item => caseMatches(item, query) && (status === "all" || (item.details?.status || "active") === status));
  return rows.length ? <div className="desk-table-scroll"><table className={compact ? "desk-table compact" : "desk-table"}><thead><tr><th>{de ? "Aktenzeichen / Angelegenheit" : "Reference / matter"}</th><th>{de ? "Beteiligte" : "Parties"}</th>{!compact && <th>{c.legalArea}</th>}<th>Status</th><th>{de ? "Frist / Wiedervorlage" : "Deadline / follow-up"}</th></tr></thead><tbody>{rows.map(item => <tr key={item.id}><td><button className="desk-record-link" onClick={() => open(item.id)}><span className="desk-reference">{item.reference}</span><strong>{item.title}</strong></button>{item.details?.responsible && <small>{item.details.responsible}</small>}</td><td><span>{item.details?.client_name || "—"}</span><small>{item.details?.opponent_name || "—"}</small></td>{!compact && <td>{c.areas.find(([key]) => key === item.details?.legal_area)?.[1] || c.areas[0][1]}</td>}<td><Status item={item} lang={lang} /></td><td><span className={item.details?.deadline && item.details.deadline < localToday() && item.details?.status !== "closed" ? "desk-overdue" : ""}>{dateLabel(item.details?.deadline, lang)}</span><small>{item.documents.length} {de ? "Dok." : "docs"} · {item.drafts.length} {de ? "Entw." : "drafts"}</small></td></tr>)}</tbody></table></div> : <Empty lang={lang}>{de ? "Keine passenden Akten. Ändern Sie den Filter oder legen Sie eine neue Akte an." : "No matching files. Change the filter or open a new file."}</Empty>;
}

export function DocumentList({ cases, lang, query = "", open, onFile, uploading, notice, onRefresh }) {
  const de = lang === "de";
  const [reviewDocument, setReviewDocument] = useState(null);
  const rows = cases.flatMap(item => item.documents.map(document => ({ ...document, caseItem: item }))).filter(row => matches(query, row.original_name, row.caseItem.reference, row.caseItem.title)).sort((a, b) => b.created_at.localeCompare(a.created_at));
  return <><div className="desk-panel-heading"><div><h2>{de ? "Dokumentenablage" : "Document storage"}</h2><p>{de ? "Originaldateien, ihrer Akte zugeordnet" : "Original files linked to their case"}</p></div>{onFile && <button className="desk-button" onClick={onFile} disabled={uploading}><IconUpload size={17} />{de ? "Dateien hinzufügen" : "Add files"}</button>}</div>{notice && <p className="storage-notice" role="status">{notice}</p>}{rows.length ? <div className="desk-table-scroll"><table className="desk-table"><thead><tr><th>{de ? "Dokument" : "Document"}</th><th>{de ? "Akte" : "Case"}</th><th>{de ? "Hochgeladen" : "Uploaded"}</th><th>{de ? "Größe" : "Size"}</th><th>{de ? "Aktion" : "Action"}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><span className="desk-file-name"><IconFileText size={19} />{row.original_name}</span><small className="desk-document-state">{row.reviewed_units ? `${row.reviewed_units} ${de ? "geprüfte Stellen" : "reviewed locations"}` : row.extraction_status === "ready" ? (de ? "Text ungeprüft" : "Text not reviewed") : row.extraction_status === "no_text" ? (de ? "OCR erforderlich" : "OCR required") : row.extraction_status === "failed" ? (de ? "Auslesen fehlgeschlagen" : "Extraction failed") : (de ? "Noch nicht ausgelesen" : "Not extracted yet")}</small></td><td><button className="desk-link" onClick={() => open(row.caseItem.id, "documents")}>{row.caseItem.reference}</button></td><td>{dateLabel(row.created_at, lang)}</td><td>{row.size_bytes < 1024 * 1024 ? `${Math.max(1, Math.round(row.size_bytes / 1024))} KB` : `${(row.size_bytes / 1024 / 1024).toFixed(1)} MB`}</td><td><div className="desk-document-actions"><button className="desk-link" aria-label={`${de ? "Text prüfen" : "Review text"}: ${row.original_name}`} onClick={() => setReviewDocument(row)}>{de ? "Text prüfen" : "Review text"}</button><a className="desk-link" href={`${API_BASE}/api/cases/${row.caseItem.id}/documents/${row.id}/download`}>{de ? "Herunterladen" : "Download"}</a></div></td></tr>)}</tbody></table></div> : <Empty lang={lang}>{de ? "Noch keine Dokumente. Laden Sie Dateien innerhalb einer Akte hoch." : "No documents yet. Upload files inside a case file."}</Empty>}{reviewDocument && <DocumentReview key={reviewDocument.id} document={reviewDocument} lang={lang} onClose={() => setReviewDocument(null)} onChanged={onRefresh} />}</>;
}

export function DraftList({ cases, lang, query = "", open, onDraft, onNew }) {
  const de = lang === "de", dc = draftCopy[lang];
  const rows = cases.flatMap(item => item.drafts.map(draft => ({ ...draft, caseItem: item }))).filter(row => matches(query, row.recipient, row.caseItem.reference, row.caseItem.title, dc.types.find(([id]) => id === row.kind)?.[1])).sort((a, b) => b.created_at.localeCompare(a.created_at));
  return <><div className="desk-panel-heading"><div><h2>{de ? "Schriftsätze & Entwürfe" : "Documents & drafts"}</h2><p>{de ? "Gespeicherte Fassungen zur weiteren Bearbeitung" : "Saved versions ready for editing"}</p></div>{onNew && <button className="desk-button" onClick={onNew}><IconPlus size={17} />{de ? "Neuer Entwurf" : "New draft"}</button>}</div>{rows.length ? <div className="desk-table-scroll"><table className="desk-table"><thead><tr><th>{de ? "Schriftsatz" : "Document"}</th><th>{de ? "Akte" : "Case"}</th><th>{dc.recipient}</th><th>{de ? "Angelegt" : "Created"}</th><th>{de ? "Aktion" : "Action"}</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{dc.types.find(([id]) => id === row.kind)?.[1] || row.kind}</strong><small>{row.language === "de" ? "Deutsch" : "English"} · {reviewLabels[lang][row.review_status || "draft"]} · v{row.version || 1}</small></td><td><button className="desk-link" onClick={() => open(row.caseItem.id, "drafts")}>{row.caseItem.reference}</button></td><td className="desk-recipient">{row.recipient || "—"}</td><td>{dateLabel(row.created_at, lang)}</td><td><button className="desk-link" onClick={() => onDraft(row, row.caseItem)}>{de ? "Bearbeiten" : "Edit"}<IconEdit size={15} /></button></td></tr>)}</tbody></table></div> : <Empty lang={lang}>{de ? "Noch keine gespeicherten Entwürfe. Erstellen Sie einen Schriftsatz in der passenden Akte." : "No saved drafts yet. Prepare a document in its case file."}</Empty>}<p className="desk-footnote">{de ? "Entwürfe werden nicht versendet oder bei einem Gericht eingereicht. Prüfen und ergänzen Sie den Text vor der Verwendung." : "Drafts are not sent or filed with a court. Review and complete the text before use."}</p></>;
}

export function PartyList({ cases, lang, query = "", open }) {
  const de = lang === "de";
  const rows = partyRows(cases).filter(row => matches(query, row.name, row.email, row.address, ...row.cases.map(item => item.reference)));
  return <><div className="desk-panel-heading"><div><h2>{de ? "Beteiligtenverzeichnis" : "Party directory"}</h2><p>{de ? "Aus den Aktenstammdaten · Kontaktdaten in der jeweiligen Akte bearbeiten" : "From case particulars · edit contact details inside the case file"}</p></div></div>{rows.length ? <div className="desk-table-scroll"><table className="desk-table"><thead><tr><th>{de ? "Name / Organisation" : "Name / organisation"}</th><th>{de ? "Rolle" : "Role"}</th><th>{de ? "Kontakt / Anschrift" : "Contact / address"}</th><th>{de ? "Zugeordnete Akten" : "Linked case files"}</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><td><strong>{row.name}</strong></td><td><span className="desk-tag">{row.role === "client" ? (de ? "Eigene Partei / Mandant" : "Own party / client") : (de ? "Gegenseite / Beteiligte" : "Opposing / other party")}</span></td><td>{row.email && <a className="desk-link" href={`mailto:${row.email}`}>{row.email}</a>}<small className="desk-address">{row.address || "—"}</small></td><td><div className="desk-case-links">{row.cases.map(item => <button key={item.id} className="desk-link" onClick={() => open(item.id, "parties")}>{item.reference}</button>)}</div></td></tr>)}</tbody></table></div> : <Empty lang={lang} />}</>;
}

export function ActivityList({ cases, lang, open, limit }) {
  const rows = activityRows(cases).slice(0, limit);
  return <ol className="desk-activity">{rows.map(row => <li key={row.id}><span className="desk-activity-dot" /><div><strong>{activityLabels[lang][row.action] || row.action}</strong>{row.detail && <p>{["draft_created", "draft_updated"].includes(row.action) ? draftCopy[lang].types.find(([id]) => id === row.detail)?.[1] || row.detail : row.detail}</p>}<button className="desk-link" onClick={() => open(row.caseItem.id, "activity")}>{row.caseItem.reference}</button><time dateTime={row.created_at}>{dateLabel(row.created_at, lang, true)}</time></div></li>)}</ol>;
}

function TaskForm({ cases, lang, saveTask, initial, onSaved }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const de = lang === "de";
  const submit = async event => {
    event.preventDefault();
    const form = event.currentTarget, fields = Object.fromEntries(new FormData(form));
    setBusy(true); setError("");
    try {
      await saveTask(fields.case_id, { title: fields.title, note: fields.note, due_on: fields.due_on || null, priority: fields.priority, ...(initial ? { completed: initial.completed } : {}) }, initial?.id);
      form.reset(); onSaved();
    } catch { setError(de ? "Speichern fehlgeschlagen. Ihre Eingaben bleiben erhalten." : "Could not save. Your entries have been retained."); } finally { setBusy(false); }
  };
  return <form className="desk-task-form" onSubmit={submit}><fieldset disabled={busy}><legend>{initial ? (de ? "Aufgabe bearbeiten" : "Edit task") : (de ? "Aufgabe / Wiedervorlage anlegen" : "Add task / follow-up")}</legend><label>{de ? "Zugeordnete Akte" : "Case file"}<select name="case_id" aria-label={de ? "Zugeordnete Akte" : "Case file"} defaultValue={initial?.caseItem.id || cases[0]?.id} disabled={Boolean(initial)}>{cases.map(item => <option key={item.id} value={item.id}>{item.reference} · {item.title}</option>)}</select></label>{initial && <input type="hidden" name="case_id" value={initial.caseItem.id} />}<label>{de ? "Aufgabe *" : "Task *"}<input name="title" required minLength={3} maxLength={200} defaultValue={initial?.title || ""} placeholder={de ? "z. B. Belege beim Mandanten anfordern" : "e.g. Request supporting documents"} /></label><div className="desk-form-grid"><label>{de ? "Fällig am" : "Due date"}<input name="due_on" type="date" defaultValue={initial?.due_on || ""} /></label><label>{de ? "Priorität" : "Priority"}<select name="priority" aria-label={de ? "Priorität" : "Priority"} defaultValue={initial?.priority || "normal"}><option value="normal">Normal</option><option value="high">{de ? "Hoch" : "High"}</option></select></label></div><label>{de ? "Notiz / Quelle" : "Note / source"}<textarea name="note" rows={2} maxLength={2000} defaultValue={initial?.note || ""} /></label>{error && <p className="storage-error" role="alert">{error}</p>}<div className="desk-form-actions">{initial && <button className="desk-button" type="button" onClick={onSaved}>{de ? "Abbrechen" : "Cancel"}</button>}<button className="desk-button solid" type="submit">{busy ? "…" : de ? "Aufgabe speichern" : "Save task"}<IconCheck size={16} /></button></div></fieldset></form>;
}

export function TaskBoard({ cases, lang, query = "", open, saveTask, compact = false }) {
  const [showCompleted, setShowCompleted] = useState(false), [editing, setEditing] = useState(null), [busyId, setBusyId] = useState(null), [error, setError] = useState("");
  const de = lang === "de", today = localToday();
  const tasks = taskRows(cases).filter(row => (showCompleted || !row.completed) && matches(query, row.title, row.note, row.caseItem.reference, row.caseItem.title));
  const deadlines = cases.filter(item => item.details?.deadline && item.details?.status !== "closed" && caseMatches(item, query)).sort((a, b) => a.details.deadline.localeCompare(b.details.deadline));
  const toggle = async row => {
    setBusyId(row.id); setError("");
    try { await saveTask(row.caseItem.id, { title: row.title, note: row.note, due_on: row.due_on, priority: row.priority, completed: !row.completed }, row.id); } catch { setError(de ? "Änderung konnte nicht gespeichert werden." : "Could not save the change."); } finally { setBusyId(null); }
  };
  return <><div className="desk-panel-heading"><div><h2>{de ? "Fristen & Aufgaben" : "Deadlines & tasks"}</h2><p>{de ? "Manuell erfasst · keine automatische Fristberechnung oder Benachrichtigung" : "Manually recorded · no automatic deadline calculation or notifications"}</p></div>{compact && <button className="desk-link" onClick={() => open(null, "tasks")}>{de ? "Alle anzeigen" : "View all"}<IconArrowUpRight size={16} /></button>}</div>{!compact && <label className="desk-checkbox"><input type="checkbox" checked={showCompleted} onChange={event => setShowCompleted(event.target.checked)} />{de ? "Erledigte Aufgaben anzeigen" : "Show completed tasks"}</label>}{error && <p role="alert" className="storage-error">{error}</p>}<div className="desk-task-board"><div className="desk-task-list">{deadlines.slice(0, compact ? 3 : undefined).map(item => <div className={`desk-task-row ${item.details.deadline < today ? "overdue" : ""}`} key={`deadline-${item.id}`}><IconCalendar size={19} /><div><strong>{item.details.deadline_note || (de ? "Erfasste Aktenfrist" : "Recorded case deadline")}</strong><button className="desk-link" onClick={() => open(item.id)}>{item.reference}</button><small>{de ? "Frist aus den Stammdaten" : "Deadline from particulars"}</small></div><time>{dateLabel(item.details.deadline, lang)}</time></div>)}{tasks.slice(0, compact ? 5 : undefined).map(row => <div key={row.id} className={`desk-task-row ${row.completed ? "completed" : row.due_on && row.due_on < today ? "overdue" : ""}`}><input type="checkbox" aria-label={`${de ? "Erledigt" : "Completed"}: ${row.title}`} checked={row.completed} disabled={Boolean(busyId)} onChange={() => toggle(row)} /><div><strong>{row.title}{row.priority === "high" && <span className="desk-priority">{de ? "Hoch" : "High"}</span>}</strong><button className="desk-link" onClick={() => open(row.caseItem.id, "tasks")}>{row.caseItem.reference}</button>{row.note && <small>{row.note}</small>}</div><div className="desk-task-date"><time>{dateLabel(row.due_on, lang)}</time>{!compact && <button className="desk-link" disabled={Boolean(busyId)} onClick={() => setEditing(row)}>{de ? "Bearbeiten" : "Edit"}</button>}</div></div>)}{!deadlines.length && !tasks.length && <Empty lang={lang}>{de ? "Keine offenen Fristen oder Aufgaben in dieser Auswahl." : "No pending deadlines or tasks in this selection."}</Empty>}</div>{!compact && cases.length > 0 && <TaskForm key={editing?.id || "new"} cases={cases} lang={lang} saveTask={saveTask} initial={editing} onSaved={() => setEditing(null)} />}</div></>;
}
