import { IconBook2, IconSearch, IconReceipt, IconBuildingBank, IconRoute, IconFileText, IconArrowUpRight } from "@tabler/icons-react";

const content = {
  de: {
    kicker: "FUNKTIONEN & RECHERCHE", title: "Von der Rechtsfrage zur nächsten Handlung.",
    intro: "Für Verbraucher, Unternehmen und Kanzleien: strukturierte Akten, nachvollziehbare Recherche und bearbeitbare Schriftsätze. Deutsch und Englisch sind die Arbeitssprachen; der lokale Quellenkatalog enthält deutsches Bundesrecht. EU-Quellen sind separat verlinkt.",
    audiences: [["Verbraucher", "Käufe, Verträge, Wohnen, Arbeit und Forderungen: Unterlagen ordnen, Rechte recherchieren und die eigene Angelegenheit verständlich vorbereiten."], ["Business", "Verträge, offene Rechnungen, Personal und Geschäftspartner: Sachverhalte dokumentieren, Risiken recherchieren und geschäftliche Korrespondenz vorbereiten."], ["Anwaltskanzleien", "Mandatsakten, Normen und Rechtsprechung: Recherche mit Fundstellen, Gegenpositionen und Verfahrensbezug vorbereiten und Schriftsatzentwürfe bearbeiten."]],
    live: "Bereits verfügbar", liveText: "Passende Registrierung für Verbraucher, Unternehmen und Kanzleien, Aktenanlage, Dateiablage mit überprüfbaren PDF/DOCX-Texten, lokaler KI-Chat mit Originalquellen und Fundstellen sowie Schriftsätze als Text oder PDF mit eigenem Briefkopf.",
    sourceStatus: "Quellensuche verfügbar", planned: "Automatische Prüfung geplant", sources: "Quellen öffnen", draftStatus: "Bearbeitbare Vorlagen verfügbar",
    tools: [
      { title: "Gesetze & Normen", sourceAvailable: true, icon: IconBook2, text: "Prüfkatalog nach Rechtsgebiet: Ansprüche, Voraussetzungen, Ausnahmen und Verfahrensregeln mit Paragraph, Fassung und Quellenbezug.", bullets: ["Zivil-, Miet- & Verbraucherrecht: BGB, EGBGB", "Handel & Unternehmen: HGB, GmbHG, InsO", "Arbeit: BGB, KSchG, BUrlG, ArbGG", "Verfahren: ZPO, GVG, FamFG, VwGO, SGG", "Weitere Gebiete: StGB, StPO, VwVfG, SGB", "EU-Recht: externe Links, noch kein Quellenadapter"], links: [["Bundesrecht", "https://www.gesetze-im-internet.de/"], ["EU-Recht", "https://eur-lex.europa.eu/homepage.html?locale=de"]] },
      { title: "Recherche, Urteile & Beschlüsse", sourceAvailable: true, icon: IconSearch, text: "Bundesgerichtsindex nach Gericht, Datum und Aktenzeichen durchsuchen; Themensuche in geladenen Volltexten. Tragende Gründe, Leitsätze, vergleichbare Sachverhalte und Gegenargumente für die Akte aufbereiten.", bullets: ["Fundstellen und Originalentscheidungen", "Unterscheidung zwischen Urteil und Beschluss", "Relevanz, Abweichungen und Instanzenzug"], links: [["Bundesgerichte", "https://www.rechtsprechung-im-internet.de/"], ["Länder & weitere Gerichte", "https://www.justiz.de/onlinedienste/rechtsprechung/index.php"]] },
      { title: "Kostenrechnungen überprüfen", icon: IconReceipt, text: "Rechnungen nach ihrer Grundlage betrachten: anwaltliche Gebühren, Gerichtskosten sowie vertragliche Forderungen und Betriebskosten.", bullets: ["RVG: Wert, Gebührentatbestand, Satz, Anrechnung", "GKG / FamGKG: Wert und Kostenansatz", "Vereinbarungen, Auslagen, Umsatzsteuer und Summen", "Verbraucherrechnungen: Vertrag, Positionen, Belege"], links: [["RVG", "https://www.gesetze-im-internet.de/rvg/"], ["GKG", "https://www.gesetze-im-internet.de/gkg_2004/"], ["FamGKG", "https://www.gesetze-im-internet.de/famgkg/"]] },
      { title: "Welches Gericht ist zuständig?", icon: IconBuildingBank, text: "Rechtsweg, sachliche und örtliche Zuständigkeit anhand von Streitgegenstand, Beteiligten, Ort und Verfahrensart untersuchen; Gericht und Kontaktweg für die Akte festhalten.", bullets: ["Zivil-, Arbeits-, Verwaltungs- oder Sozialgericht", "Gerichtsstand, Sonderzuständigkeiten, Instanz", "Gerichtliches Aktenzeichen getrennt führen"], links: [["Justizverzeichnisse", "https://www.justiz.de/service/verzeichnisse/index.php"]] },
      { title: "Was ist wo und wie erreichbar?", icon: IconRoute, text: "Handlungswege vom gewünschten Ergebnis aus vergleichen: welche Stelle, welcher Antrag, welche Unterlagen, welche Form und welche Risiken müssen geklärt werden?", bullets: ["Anschreiben, Verhandlung, Schlichtung, Mahnverfahren", "Klage, Antrag, Widerspruch oder Rechtsmittel", "Voraussetzungen, Beweise, Fristen und Kosten", "Fristen derzeit manuell erfassen"], links: [["Justiz-Onlinedienste", "https://www.justiz.de/onlinedienste/index.php"]] },
      { title: "Klagen & Anschreiben entwerfen", icon: IconFileText, available: true, text: "Bearbeitbare Vorlagen übernehmen Aktenzeichen, Beteiligte, Sachverhalt und Ziel aus der Akte. Empfänger frei wählen: Gericht, Regierung / Behörde, Kanzlei, Unternehmen oder Privatperson.", bullets: ["Klage-, Antrags- und Widerspruchsentwürfe", "Allgemeine Anschreiben und Stellungnahmen", "Empfänger, Betreff und Anlagen ergänzen", "Fehlende Angaben als sichtbare Platzhalter", "Speichern und als Text oder PDF mit Briefkopf herunterladen"], links: [] },
    ],
    note: "Die lokale KI strukturiert Angaben und bereitet Entwürfe vor. Antworten sind rechtlich nicht geprüft. Ausgewählte, zuvor überprüfte PDF/DOCX-Textauszüge können mit Seiten- oder Abschnittsbezug eingebunden werden. Bundesrecht und veröffentlichte Bundesentscheidungen können lokal gesucht und als Originalpassagen eingebunden werden. Technische Quellen- und Verweisprüfung ersetzt keine Rechtsprüfung. OCR, Gebührenberechnung und Zuständigkeitsprüfung sind noch nicht angebunden. Quellen decken nicht alle Entscheidungen ab; Mexiko und andere Rechtsordnungen benötigen eigene Quellen und Regeln.",
  },
  en: {
    kicker: "FEATURES & RESEARCH", title: "From a legal question to the next action.",
    intro: "For consumers, businesses and law firms: structured case files, traceable research and editable documents. German and English are the working languages; the local catalogue contains German federal law. EU sources are linked separately.",
    audiences: [["Consumers", "Purchases, contracts, housing, work and claims: organise evidence, research rights and prepare your personal matter clearly."], ["Business", "Contracts, unpaid invoices, employees and partners: document facts, research risks and prepare business correspondence."], ["Law firms", "Client files, legislation and case law: prepare research with references, opposing positions and procedural context, and edit document drafts."]],
    live: "Available now", liveText: "Tailored registration for consumers, businesses and law firms, case intake, file storage with reviewable PDF/DOCX text, local AI chat with original sources and passages, and drafts as text or PDF using your letterhead.",
    sourceStatus: "Source search available", planned: "Automatic review planned", sources: "Open sources", draftStatus: "Editable templates available",
    tools: [
      { title: "Legislation & provisions", sourceAvailable: true, icon: IconBook2, text: "Research catalogue by area of law: claims, requirements, exceptions and procedural rules with provision, version and source references.", bullets: ["Civil, tenancy & consumer law: BGB, EGBGB", "Commerce & companies: HGB, GmbHG, InsO", "Employment: BGB, KSchG, BUrlG, ArbGG", "Procedure: ZPO, GVG, FamFG, VwGO, SGG", "Other areas: StGB, StPO, VwVfG, SGB", "EU law: external links; no source adapter yet"], links: [["German federal law", "https://www.gesetze-im-internet.de/"], ["EU law", "https://eur-lex.europa.eu/homepage.html?locale=en"]] },
      { title: "Research, judgments & orders", sourceAvailable: true, icon: IconSearch, text: "Search the federal index by court, date and reference; topic search uses downloaded full texts. Prepare reasoning, headnotes, comparable facts and opposing arguments for the file.", bullets: ["References and original decisions", "Distinguish judgments from orders", "Relevance, differences and appeal history"], links: [["Federal courts", "https://www.rechtsprechung-im-internet.de/"], ["State & other courts", "https://www.justiz.de/onlinedienste/rechtsprechung/index.php"]] },
      { title: "Review costs & invoices", icon: IconReceipt, text: "Review an invoice against its basis: lawyer fees, court costs, contractual charges and operating costs.", bullets: ["RVG: value, fee item, rate and credits", "GKG / FamGKG: value and court charges", "Agreements, expenses, VAT and totals", "Consumer invoices: contract, items and evidence"], links: [["RVG", "https://www.gesetze-im-internet.de/rvg/"], ["GKG", "https://www.gesetze-im-internet.de/gkg_2004/"], ["FamGKG", "https://www.gesetze-im-internet.de/famgkg/"]] },
      { title: "Which court has jurisdiction?", icon: IconBuildingBank, text: "Examine the appropriate court system, subject-matter and territorial jurisdiction using the dispute, parties, location and proceedings; record the court and contact route.", bullets: ["Civil, labour, administrative or social court", "Venue, special jurisdiction and instance", "Keep the court reference separate"], links: [["Justice directories", "https://www.justiz.de/service/verzeichnisse/index.php"]] },
      { title: "What can you achieve, where and how?", icon: IconRoute, text: "Compare routes from the desired outcome: which authority, application, documents, form and risks need to be clarified?", bullets: ["Letters, negotiation, conciliation, payment orders", "Claim, application, objection or appeal", "Requirements, evidence, deadlines and costs", "Record deadlines manually for now"], links: [["Justice online services", "https://www.justiz.de/onlinedienste/index.php"]] },
      { title: "Draft claims & correspondence", icon: IconFileText, available: true, text: "Editable templates use the file reference, parties, facts and objective. Choose any recipient: court, government / authority, law firm, business or individual.", bullets: ["Claim, application and objection drafts", "General letters and written responses", "Complete recipient, subject and attachments", "Visible placeholders for missing details", "Save and download as text or letterhead PDF"], links: [] },
    ],
    note: "Local AI structures particulars and prepares drafts. Answers are not legally reviewed. Selected, transcription-reviewed PDF/DOCX excerpts can be included with page or section references. Federal statutes and published federal decisions can supply locally searched original passages. Technical source and citation checks do not establish legal correctness. OCR, fee calculation and jurisdiction checks are not connected yet. Sources do not cover every decision; Mexico and other legal systems need their own sources and rules.",
  },
};

export function FeatureOverview({ lang, onDraft }) {
  const c = content[lang];
  return <section className="feature-section research-features" id="features">
    <div className="section-heading"><p className="section-kicker">{c.kicker}</p><h2>{c.title}</h2><p className="feature-intro">{c.intro}</p></div>
    <div className="audience-features">{c.audiences.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div>
    <div className="availability-line"><strong>{c.live}</strong><span>{c.liveText}</span></div>
    <div className="feature-cards research-cards">{c.tools.map(({ title, icon: Icon, text, bullets, links, available, sourceAvailable }) => <article key={title}><div className="feature-card-top"><Icon size={24} /><span className={`feature-status ${available || sourceAvailable ? "available" : ""}`}>{available ? c.draftStatus : sourceAvailable ? c.sourceStatus : c.planned}</span></div><h3>{title}</h3><p>{text}</p><ul>{bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul><div className="feature-links">{links.map(([label, href]) => <a key={href} href={href} target="_blank" rel="noreferrer">{label}<IconArrowUpRight size={14} /></a>)}{available && <button className="text-link" onClick={onDraft}>{lang === "de" ? "Entwurf vorbereiten" : "Prepare a draft"}<IconArrowUpRight size={14} /></button>}</div></article>)}</div>
    <p className="feature-footnote">{c.note}</p>
  </section>;
}
