// Manual working papers. These do not invoke a model or complete a legal review.
export const legalWorkflows = {
  de: [
    { id: "intake", title: "Fallaufnahme & Belege", purpose: "Sachverhalt, Auftrag und fehlende Nachweise strukturieren.", steps: ["Chronologie mit Datum, Behauptung und Dokument / Seite erstellen.", "Eigene Partei, Gegenseite und Verfahrensrolle prüfen.", "Bestätigte, streitige und noch offene Tatsachen trennen.", "Fehlende Unterlagen und nächste Aufgaben festhalten."] },
    { id: "research", title: "Gesetze, Urteile & Beschlüsse", purpose: "Eine konkrete Rechtsfrage mit nachprüfbaren Fundstellen bearbeiten.", steps: ["Rechtsfrage, Rechtsordnung und maßgeblichen Sachverhaltszeitpunkt eingrenzen.", "Anwendbare Gesetzesfassung und aktuelle Originalquelle prüfen.", "Entscheidungen mit Gericht, Art, Datum, Aktenzeichen und tragender Passage erfassen.", "Vergleichbarkeit, Gegenargumente und offene Fragen dokumentieren."] },
    { id: "jurisdiction", title: "Zuständigkeit & Verfahrensweg", purpose: "Klären, welche Stelle mit welchem Antrag erreicht werden kann.", steps: ["Ziel, Parteien, Orte, Streitgegenstand und Auslandsbezug prüfen.", "Rechtsweg sowie sachliche, örtliche und internationale Zuständigkeit getrennt untersuchen.", "Aktuelle Wertgrenzen und Sonderzuständigkeiten an Originalquellen prüfen.", "Form, Vertretung, Vorverfahren und zulässigen Einreichungsweg festhalten."] },
    { id: "costs", title: "Kosten- & Rechnungsprüfung", purpose: "Berechnungsgrundlage, Belege und Abweichungen prüfen.", steps: ["Rechnung als RVG, Gerichtskosten, Vereinbarung, normale Rechnung oder Betriebskosten einordnen.", "Positionen, Wert, Satz, Auslagen, Steuer, Vorschüsse und Belege erfassen.", "Anwendbare Fassung, Tabelle, Anrechnung und Vergütungsgrundlage prüfen.", "Rechnung mit nachvollziehbarer Dezimalrechnung kontrollieren; Wertungsfragen getrennt halten."] },
    { id: "drafting", title: "Klage, Antrag & Korrespondenz", purpose: "Den passenden Schriftsatz mit überprüfbaren Angaben vorbereiten.", steps: ["Empfänger, Verfahrensart, Zuständigkeit und gewünschte Handlung klären.", "Parteien, Antrag, Sachverhalt und zugeordnete Beweise zusammentragen.", "Interne Aktennummer und gerichtliches / gegnerisches Aktenzeichen getrennt verwenden.", "Lücken, Fundstellen, Beträge, Anlagen, Form und Unterschrift vor Verwendung prüfen."] },
    { id: "deadlines", title: "Fristen & Wiedervorlage", purpose: "Zeitkritische Angaben und ihre Quellen nachvollziehbar aufnehmen.", steps: ["Rechtliche Frist und interne Wiedervorlage unterscheiden.", "Zugang / Zustellung, auslösendes Ereignis, Rechtsgrundlage und Belege erfassen.", "Ungeprüfte Daten, Kalenderannahmen und offene Fragen ausdrücklich kennzeichnen.", "Bestätigte Daten manuell in der Akte bzw. Aufgabenliste eintragen; keine automatische Überwachung."] },
  ],
  en: [
    { id: "intake", title: "Intake & evidence", purpose: "Structure facts, instructions and missing evidence.", steps: ["Build a chronology with date, assertion and document / page.", "Check own party, opposing party and procedural roles.", "Separate confirmed, disputed and unresolved facts.", "Record missing documents and next tasks."] },
    { id: "research", title: "Legislation, judgments & orders", purpose: "Research a specific legal question with traceable sources.", steps: ["Define question, jurisdiction and relevant factual date.", "Check the applicable statutory version and current primary source.", "Record court, decision type, date, reference and supporting passage.", "Document factual relevance, counterarguments and unresolved questions."] },
    { id: "jurisdiction", title: "Jurisdiction & procedural route", purpose: "Clarify the competent body and appropriate application.", steps: ["Check objective, parties, locations, subject matter and cross-border factors.", "Examine court system, subject-matter, territorial and international jurisdiction separately.", "Verify current value thresholds and special jurisdiction at primary sources.", "Record form, representation, preliminary proceedings and permitted filing channel."] },
    { id: "costs", title: "Costs & invoice review", purpose: "Check charging basis, evidence and discrepancies.", steps: ["Classify statutory lawyer fees, court costs, an agreement, a regular invoice or operating costs.", "Extract items, value, rate, expenses, tax, advances and evidence.", "Check applicable version, table, credits and fee agreement.", "Recalculate with traceable decimal arithmetic and separate legal valuation questions."] },
    { id: "drafting", title: "Claims, applications & letters", purpose: "Prepare the appropriate document using checked particulars.", steps: ["Clarify recipient, proceedings, jurisdiction and requested action.", "Assemble parties, request, facts and supporting evidence.", "Keep internal, court and opposing-party references separate.", "Review gaps, sources, amounts, exhibits, form and signature before use."] },
    { id: "deadlines", title: "Deadlines & follow-up", purpose: "Record time-sensitive information and its provenance.", steps: ["Distinguish a legal deadline from an internal follow-up.", "Record receipt / service, triggering event, legal basis and evidence.", "Clearly mark unverified dates, calendar assumptions and unresolved questions.", "Enter confirmed dates manually in particulars or tasks; no automatic monitoring."] },
  ],
};

export function researchBrief(item, lang, workflowId) {
  const de = lang === "de", workflow = legalWorkflows[lang].find(entry => entry.id === workflowId);
  if (!item || !workflow) throw new Error("A case and known workflow are required");
  const d = item.details || {};
  return [
    `${de ? "ARBEITSPAPIER – NOCH NICHT GEPRÜFT" : "WORKING PAPER – NOT YET REVIEWED"}\n${workflow.title}`,
    `${de ? "Interne Akte" : "Internal reference"}: ${item.reference}\n${de ? "Angelegenheit" : "Matter"}: ${item.title}\n${de ? "Rechtsordnung" : "Jurisdiction"}: ${d.jurisdiction || "DE"}\n${de ? "Gerichtliches Aktenzeichen" : "Court reference"}: ${d.court_reference || "[—]"}\n${de ? "Aktenzeichen der Gegenseite" : "Opposing party reference"}: ${d.opponent_reference || "[—]"}`,
    `${de ? "ZIEL / AUFTRAG" : "OBJECTIVE / INSTRUCTIONS"}\n${d.objective || (de ? "[Ziel ergänzen]" : "[Complete objective]")}`,
    `${de ? "SACHVERHALT – ANGABEN AUS DER AKTE" : "FACTS – ENTERED IN THE CASE FILE"}\n${item.description}`,
    `${de ? "PRÜFSCHRITTE" : "REVIEW STEPS"}\n${workflow.steps.map((step, index) => `${index + 1}. ${step}\n   ${de ? "Ergebnis / Beleg: [ergänzen]" : "Finding / evidence: [complete]"}`).join("\n\n")}`,
    de ? "QUELLENPROTOKOLL\n[Norm / Fassung bzw. Gericht / Datum / Az. / Fundstelle]\n[Original-URL / Seite / Randnummer / geprüft am / Verifikationsstatus]" : "SOURCE LEDGER\n[Provision / version or court / date / reference / citation]\n[Primary URL / page / paragraph / checked on / verification status]",
    de ? "ERGEBNIS & OFFENE FRAGEN\n[Noch zu erarbeiten – keine automatische Analyse durchgeführt.]\n[Nächste Schritte und notwendige Prüfung ergänzen.]" : "FINDINGS & OPEN QUESTIONS\n[To be completed – no automatic analysis has been performed.]\n[Complete next steps and required review.]",
  ].join("\n\n");
}
