export function ResearchDocumentPicker({ lang, documents = [], selected, setSelected, busy, onDocuments }) {
  const de = lang === "de";
  return <fieldset className="research-document-picker" disabled={busy}><legend>{de ? "Dokumente für diese Frage" : "Documents for this question"}</legend><p>{de ? "Nur geprüfte Stellen aus höchstens 8 ausgewählten Dateien. Die KI erhält begrenzte Auszüge; keine vollständige Aktenprüfung." : "Only reviewed passages from up to 8 selected files. AI receives limited excerpts, not a full case review."}</p>{documents.length ? documents.map(document => <label key={document.id}><input type="checkbox" checked={selected.includes(document.id)} disabled={!document.reviewed_units || !selected.includes(document.id) && selected.length >= 8} onChange={event => setSelected(current => event.target.checked ? [...current, document.id] : current.filter(id => id !== document.id))} /><span>{document.original_name}<small>{document.reviewed_units ? `${document.reviewed_units} ${de ? "geprüfte Stellen" : "reviewed locations"}` : (de ? "Text zuerst in Dokumente prüfen" : "Review text in Documents first")}</small></span></label>) : <p>{de ? "Noch keine Dateien in dieser Akte." : "No files in this case yet."}</p>}{onDocuments && <button type="button" className="desk-link" onClick={onDocuments}>{de ? "Dokumente öffnen & Text prüfen →" : "Open documents & review text →"}</button>}</fieldset>;
}

export function ResearchSourceList({ lang, sources = [] }) {
  if (!sources.length) return null;
  const de = lang === "de";
  return <details className="research-used-sources"><summary>{de ? "Verwendete Dokumentstellen" : "Document passages supplied"} ({sources.length})</summary><p>{de ? "Gespeicherte Auszüge dieser Anfrage. Spätere Textkorrekturen ändern diese Dokumentation nicht. Dies sind Dokumentbelege, keine verifizierten Rechtsquellen." : "Saved excerpts for this request. Later text corrections do not change this record. These are document evidence, not verified legal sources."}</p>{sources.map(source => <article key={`${source.document_id}-${source.unit_no}`}><strong>{source.filename} · {source.unit_kind === "page" ? (de ? "PDF-Seite" : "PDF page") : (de ? "DOCX-Abschnitt" : "DOCX section")} {source.unit_no}</strong><pre>{source.text}</pre>{source.excerpt_truncated && <small>{de ? "Begrenzter Auszug" : "Limited excerpt"}</small>}</article>)}</details>;
}
